name: Ruff

on:
  push:
    branches:
      - 'main'
    paths:
      - 'subdomain_watcher/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ruff.yaml'

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Run Ruff Linter
        run: |
          uv sync
          uv run ruff check .

      - name: Run Ruff Formatter
        run: uv run ruff format --check .
